# Generated by Django 2.0.5 on 2018-07-31 18:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MpUserProfile',
            fields=[
                ('user_id', models.CharField(help_text='the user Id goes here', max_length=20)),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular user', primary_key=True, serialize=False)),
                ('name_from_mp', models.CharField(default='noname', max_length=100)),
                ('export_url', models.CharField(default='noname', max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='connections',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_creator_set', to='users.MpUserProfile'),
        ),
        migrations.AddField(
            model_name='connections',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_set', to='users.MpUserProfile'),
        ),
    ]
