# Generated by Django 2.0.5 on 2018-07-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpuserprofile',
            name='nameFromMp',
            field=models.CharField(default='', max_length=100),
        ),
    ]
