# Generated by Django 2.0.5 on 2018-07-20 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_mpuserprofile_namefrommp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpuserprofile',
            name='nameFromMp',
        ),
    ]
