# Generated by Django 2.0.5 on 2018-07-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_mpuserprofile_namefrommp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpuserprofile',
            name='name_from_mp',
            field=models.CharField(default='', max_length=100),
        ),
    ]
