# Generated by Django 2.0.5 on 2018-07-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_mpuserprofile_name_from_mp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpuserprofile',
            name='export_url',
            field=models.CharField(default='', max_length=300),
        ),
    ]
