# Generated by Django 2.0.5 on 2018-07-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_mpuserprofile_export_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpuserprofile',
            name='export_url',
            field=models.CharField(default='noname', max_length=300),
        ),
        migrations.AlterField(
            model_name='mpuserprofile',
            name='name_from_mp',
            field=models.CharField(default='noname', max_length=100),
        ),
    ]
