# Generated by Django 2.0.5 on 2018-07-14 00:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userTick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this tick', primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('route_name', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=15)),
                ('notes', models.CharField(max_length=300)),
                ('route_url', models.CharField(max_length=300)),
                ('route_id', models.CharField(max_length=15)),
                ('pitches', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('public_rating', models.IntegerField()),
                ('my_rating', models.IntegerField()),
                ('style', models.CharField(max_length=100)),
                ('lead_style', models.CharField(max_length=100)),
                ('route_type', models.CharField(max_length=100)),
                ('my_difficulty', models.CharField(max_length=15)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tick_creator', to='users.MpUserProfile')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='users.MpUserProfile')),
            ],
        ),
    ]
