# Generated by Django 2.0.5 on 2018-07-31 18:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastUpdatedDate', models.DateTimeField(auto_now_add=True)),
                ('needsToBeUpdatedStatus', models.BooleanField(default=True)),
                ('tickFeedOwner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tick_feed_owner', to='users.MpUserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='userTick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this tick', primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('route_name', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=15)),
                ('notes', models.CharField(blank=True, max_length=300, null=True)),
                ('route_url', models.CharField(max_length=300)),
                ('route_id', models.CharField(max_length=15)),
                ('pitches', models.IntegerField(default=1)),
                ('location', models.CharField(max_length=100)),
                ('public_rating', models.FloatField(blank=True, null=True)),
                ('my_rating', models.FloatField(blank=True, null=True)),
                ('style', models.CharField(blank=True, max_length=100, null=True)),
                ('lead_style', models.CharField(blank=True, max_length=100, null=True)),
                ('route_type', models.CharField(blank=True, max_length=100, null=True)),
                ('my_difficulty', models.CharField(blank=True, max_length=15, null=True)),
                ('user_name_from_mp', models.CharField(blank=True, max_length=15, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tick_creator', to='users.MpUserProfile')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='users.MpUserProfile')),
            ],
        ),
    ]
