# Generated by Django 2.0.5 on 2018-07-14 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticksApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertick',
            name='lead_style',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='usertick',
            name='my_difficulty',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='usertick',
            name='my_rating',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='usertick',
            name='notes',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='usertick',
            name='partner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='users.MpUserProfile'),
        ),
        migrations.AlterField(
            model_name='usertick',
            name='pitches',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usertick',
            name='public_rating',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='usertick',
            name='route_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='usertick',
            name='style',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
