# Generated by Django 2.0.5 on 2018-07-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticksApi', '0003_auto_20180714_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertick',
            name='my_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertick',
            name='public_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
