# Generated by Django 2.0.5 on 2018-07-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticksApi', '0004_auto_20180720_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertick',
            name='user_name_from_mp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
